config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  get 'toppages/index'

  resources :users, only: [:index, :show]
  resources :articles

  root to: 'toppages#index'

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.try(:admin?)
      can :access, :rails_admin
      can :manage, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user

  mount_uploader :video, VideoUploader

  validates :title, presence: true, length: { maximum: 255 }
  validates :video, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # signup時にnameも追加で許可する
  before_action :configure_permitted_parameters, if: :devise_controller?

  def require_user_logged_in
    unless user_signed_in?
      redirect_to root_url
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy]

  def show
    @article = Article.find(params[:id])
    @articles = Article.order('created_at DESC').page(params[:page])
    @user = @article.user
  end

  def new
    @article = current_user.articles.build
  end

  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      flash[:success] = "動画を投稿しました。"
      redirect_to root_url
    else
      flash.now[:danger] = "動画の投稿に失敗しました。"
      render :new
    end
  end

  def destroy
    @article.destroy
    flash[:success] = '動画を削除しました。'
    redirect_to root_url
  end
  
  private
  
  def article_params
    params.require(:article).permit(:title, :video, :description)
  end

  def correct_user
    @article = current_user.articles.find_by(id: params[:id])
    unless @article
      redirect_to root_url
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    if user_signed_in?
      @articles = Article.order('created_at DESC').page(params[:page])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in
  
  def index
    @users = User.all.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @articles = @user.articles.order('created_at DESC').page(params[:page])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}&d=mp"
  end
end

app/views/articles/_articles.html.erb
<ul class="media-list">
  <% articles.each do |article| %>
    <li class="media">
      <div class="media-body">
        <div>
          <%= link_to article_path(article) do %>
            <%= image_tag(article.video_url(:screenshot).to_s, id: "video", :alt => "screenshot") %>
          <% end %>
        </div>
        <div>
          <h5 class="title"><%= article.title %></h5>
        </div>
        <div class="description">
          <%= article.description %>
        </div>
        <div>
          <img src="<%= gravatar_url(article.user, size: 30) %>" alt="" class="img-circle">
          <%= link_to article.user.name, user_path(article.user) %>
        </div>
      </div>
    </li>
  <% end %>
  <%= paginate articles %>
</ul>

app/views/articles/new.html.erb
<div class="row">
  <div class="col-md-offset-3 col-md-6">
    <%= form_for(@article) do |f| %>
      <div class="form-group">
        <%= f.label :title, 'タイトル' %>
        <%= f.text_area :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :video, '動画' %>
        <%= f.file_field :video, :accept => 'video/*' %>
      </div>

      <div class="form-group">
        <%= f.label :description, '動画の説明' %>
        <%= f.text_area :description, class: 'form-control', rows: 5 %>
      </div>

      <%= f.submit 'Post', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/articles/show.html.erb
<div class="row">
  <aside class="col-md-8">
    <div>
      <%= link_to @article.video_url.to_s do %>
        <%= image_tag(@article.video_url(:screenshot).to_s, id: "video", :alt => "screenshot") %>
      <% end %>
    </div>
    <h3><%= @article.title %></h3>
    <div class="article-desc">
      <%= @article.description %>
    </div>
    <div>
      <img src="<%= gravatar_url(@article.user, size: 30) %>" alt="" class="img-circle">
      <%= link_to @article.user.name, user_path(@article.user) %>
    </div>
    <div class="delete-btn">
      <% if current_user == @article.user %>
        <%= link_to "動画を削除する", @article, method: :delete, data: { confirm: "本当によろしいですか？" }, class: 'btn btn-danger btn-xs' %>
      <% end %>
    </div>
  </aside>
  <div class="col-md-4">
    <h4>関連動画</h4>
    <%= render 'articles/articles', articles: @articles %>
  </div>
</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-default navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">VideoApp</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "My Page", user_path(current_user) %></li>
                <% if current_user.try(:admin?) %>
                  <li><%= link_to "管理者画面", rails_admin_path %></li>
                <% end %>
                <li role="separator" class="divider"></li>
                <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Signup", new_user_registration_path %></li>
            <li><%= link_to "Login", new_user_session_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>VideoApp</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/toppages/index.html.erb
<% if user_signed_in? %>
  <div class="row">
    <div class="col-md-offset-2 col-md-8">
      <div class="media">
        <div class="media-body">
          <h3>動画一覧</h3>
        </div>
        <div class="media-right">
          <div class="post-btn">
            <%= link_to "新規投稿", new_article_path, class: 'btn btn-primary btn-md' %>
          </div>
        </div>
      </div>
      <%= render 'articles/articles', articles: @articles %>
    </div>
  </div>
<% else %>
  <div class="center jumbotron">
    <div class="text-center">
      <h1>Video App</h1>
      <%= link_to "Log in", new_user_session_path, class: "btn btn-lg btn-primary" %>
    </div>
  </div>
<% end %>

app/views/users/_users.html.erb
<% if users.any? %>
  <ul class="media-list">
    <% users.each do |user| %>
      <li class="media">
        <div class="media-left">
          <img src="<%= gravatar_url(user, size: 50) %>" alt="" class="img-circle">
        </div>
        <div class="media-body">
          <div>
            <%= user.name %>
          </div>
          <div>
            <p><%= link_to 'View profile', user_path(user) %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate users %>
<% end %>

app/views/users/index.html.erb
<div class="row">
  <div class="col-md-offset-3 col-md-6">
    <h3>ユーザ一覧</h3>
    <%= render 'users', users: @users %>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-profile">
  <div class="icon text-center">
    <img src="<%= gravatar_url(@user, size: 100) %>" alt="" class="img-circle">
  </div>
  <div class="text-center">
    <h1><%= @user.name %></h1>
  </div>
</div>

<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <h3>動画一覧</h3>
    <%= render 'articles/articles', articles: @articles %>
  </div>
</div>